---
- name: Setup frontend load-balancer tier
  hosts: frontends
  gather_facts: false
  become: yes
  tags:
    - stage5
    - frontends

  roles:
    - common
    - frontend-tier

- name: Setup app tier
  hosts: apps
  gather_facts: false
  become: yes
  tags:
    - stage5
    - apps

  roles:
    - common
    - app-tier

- name: Setup database tier
  hosts: appdbs
  become: yes
  tags:
    - stage5
    - databases

  roles:
    - common
    - geerlingguy.postgresql
...
